### ISSUE TITLE
Double click does not work with the latest version of leaflet

### ISSUE THREAD

**Issue by dbaq** [azavea/Leaflet.favorDoubleClick#4]
Hey @RickMohr,

Thanks for sharing this plugin, it is really something in leaflet. I can't make the double click work with the latest version of leaflet (https://github.com/Leaflet/Leaflet/commit/21701a6faef880403b7ecd80d3fa35ca814b3123),  the click with the delay is working, but the zoom does not work.

Any idea? thanks?

**Comment by RickMohr** [comment]
The plugin is working again with Leaflet 1.0 Beta 2.
