### ISSUE TITLE
Overwriting L.DomEvent._on leading to different function handles for event listeners 

### ISSUE THREAD

**Issue by j4zz** [azavea/Leaflet.favorDoubleClick#7]
Hey,

first of all thank you for this useful plugin.

# Description

For me, the [overwriting of `L.DomEvent._on`](https://github.com/azavea/Leaflet.favorDoubleClick/blob/master/src/L.favorDoubleClick.js#L33) leads to me not being able to remove **click** event listeners anymore, since Leaflet [creates different ids for them](https://github.com/Leaflet/Leaflet/blob/093d77217ea8579f0b8e5c6d5303bed8cd29e619/src/dom/DomEvent.js#L45) when using the overwritten `L.DomEvent._on` from [Leaflet.favorDoubleClick](https://github.com/azavea/Leaflet.favorDoubleClick).

Since the id that is created for the event listener differs from the one that is [used in  `L.DomEvent._off`](https://github.com/Leaflet/Leaflet/blob/093d77217ea8579f0b8e5c6d5303bed8cd29e619/src/dom/DomEvent.js#L96), the event handler can’t be removed again.

# Reproducing

Reproducing the bug should be as simple as:

```js
L.favorDoubleClick.enable();

var favorOverwriteBug = function () {
  console.log('bug');
};

L.DomEvent.addListener(this._map, 'click', favorOverwriteBug, this);
L.DomEvent.removeListener(this._map, 'click', favorOverwriteBug, this);
```

If you see `bug` being printed to the console on click, the event listener was not correctly removed.

# Workaround

In my case I toggle certain functionality, and therefore it is okay for me to disable favorDoubleClick while this functionality is on. In case it is disabled, I don’t wrap the function during `L.DomEvent._on`, and therefore don’t let Leaflet create a different handle id for it, so it can be removed again.

```js
L.DomEvent._on = function (obj, type, fn, context) {
  if (L.favorDoubleClick.isEnabled()) {
    if (type === 'click') {
      fn = makeSingleNotMultiClickHandler(fn);
    }
  }
[...]
```

# Possible Solutions

I haven’t looked even further into the code, but it seems to me that the heart of the issue lies in wrapping the function (`fn = makeSingleNotMultiClickHandler(fn);`), which leads to Leaflet creating a different id for it on the `obj["_leaflet_events"]` and therefore makes it impossible to cleanly remove it if you call `removeEventListener` with the same function.

Therefore, as far as I can tell, either the wrapping needs to be removed, the id generation/stamping changed, or `L.DomEvent._off` changed so it can handle the id difference.

**Comment by RickMohr** [comment]
Thanks for the detailed writeup.
